name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  JOB: ${{ secrets.JOB }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/miles-and-promotions-scrapers/miles-and-promotions-scrapers:latest .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/miles-and-promotions-scrapers/miles-and-promotions-scrapers:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          job: "${{ env.JOB }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/miles-and-promotions-scrapers/miles-and-promotions-scrapers:latest"
          env_vars: |-
            PROJECT_ID=${{ env.PROJECT_ID }}
            REGION=${{ env.REGION }}
            JOB=${{ env.JOB }}